"""Initial migration

Revision ID: 3b02be3813b2
Revises:
Create Date: 2025-11-30 21:58:14.630562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b02be3813b2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    # Define Enums
    userrole = postgresql.ENUM("Client", "Admin", "Super Admin", name="userrole")
    userrole.create(op.get_bind(), checkfirst=True)

    cardtype = postgresql.ENUM("Uzcard", "Humo", "Visa", "Mastercard", name="cardtype")
    cardtype.create(op.get_bind(), checkfirst=True)

    goalstatus = postgresql.ENUM("Active", "Achieved", "Cancelled", name="goalstatus")
    goalstatus.create(op.get_bind(), checkfirst=True)

    goalpriority = postgresql.ENUM("Low", "Medium", "High", name="goalpriority")
    goalpriority.create(op.get_bind(), checkfirst=True)

    transactionstatus = postgresql.ENUM(
        "APPROVED",
        "DECLINED",
        "PENDING",
        "CANCELED",
        "VOIDED",
        "SETTLED",
        "REFUNDED",
        name="transactionstatus",
    )
    transactionstatus.create(op.get_bind(), checkfirst=True)

    transactiontype = postgresql.ENUM(
        "P2P_TRANSFER",
        "P2M_PAYMENT",
        "WALLET_TOPUP",
        "WALLET_PAYOUT",
        "REFUND",
        "REVERSAL",
        "ATM_WITHDRAWAL",
        name="transactiontype",
    )
    transactiontype.create(op.get_bind(), checkfirst=True)

    transactiondirection = postgresql.ENUM(
        "OUTGOING", "INCOMING", name="transactiondirection"
    )
    transactiondirection.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("family_size", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "Client", "Admin", "Super Admin", name="userrole", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("card_name", sa.String(length=50), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "card_type",
            postgresql.ENUM(
                "Uzcard",
                "Humo",
                "Visa",
                "Mastercard",
                name="cardtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("expiration_date", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_removed", sa.Boolean(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("target_amount", sa.Float(), nullable=False),
        sa.Column("current_amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Active", "Achieved", "Cancelled", name="goalstatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "Low", "Medium", "High", name="goalpriority", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("merchant", sa.String(length=100), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "APPROVED",
                "DECLINED",
                "PENDING",
                "CANCELED",
                "VOIDED",
                "SETTLED",
                "REFUNDED",
                name="transactionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column(
            "transaction_type",
            postgresql.ENUM(
                "P2P_TRANSFER",
                "P2M_PAYMENT",
                "WALLET_TOPUP",
                "WALLET_PAYOUT",
                "REFUND",
                "REVERSAL",
                "ATM_WITHDRAWAL",
                name="transactiontype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "transaction_direction",
            postgresql.ENUM(
                "OUTGOING", "INCOMING", name="transactiondirection", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("sender_info", sa.JSON(), nullable=True),
        sa.Column("receiver_info", sa.JSON(), nullable=True),
        sa.Column("metadata_info", sa.JSON(), nullable=True),
        sa.Column("gateway", sa.String(length=50), nullable=True),
        sa.Column("rrn", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("goals")
    op.drop_table("cards")
    op.drop_table("users")

    # Drop Enums
    from sqlalchemy.dialects import postgresql

    postgresql.ENUM(name="transactiondirection").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="transactiontype").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="transactionstatus").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="goalpriority").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="goalstatus").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="cardtype").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
